services:
  findr-api:
    build:
      context: ./apps/findr-api
    environment:
      SURREALDB_URL: http://surrealdb:8000/rpc
      OPENSEARCH_URL: http://opensearch:9200
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - surrealdb
      - opensearch
      - redis
    ports:
      - "8000:8000"

  findr-ui:
    build:
      context: ./apps/findr-liferay-client-extension
    environment:
      VITE_FINDR_API_BASE: http://localhost:8000
    depends_on:
      - findr-api
    ports:
      - "5173:5173"

  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log info --user root --pass root memory
    ports:
      - "8001:8000"

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "OpenAutonomyX123!"
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
